// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyANOCghKNGMNOhff6DEv5c1epmy09RsVnE',
    appId: '1:579134301857:web:cea2c6bc82661bb33e72e0',
    messagingSenderId: '579134301857',
    projectId: 'studentdata-d260d',
    authDomain: 'studentdata-d260d.firebaseapp.com',
    storageBucket: 'studentdata-d260d.firebasestorage.app',
    measurementId: 'G-VT90517BD3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDfURkIZT42fkNFlXBsxed_XOXUb1J7H8Y',
    appId: '1:579134301857:android:8f6c656eb4fdf6df3e72e0',
    messagingSenderId: '579134301857',
    projectId: 'studentdata-d260d',
    storageBucket: 'studentdata-d260d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCUeGJUtcItWcSFstGLdg_bwbHnulobhQg',
    appId: '1:579134301857:ios:af306925da786f343e72e0',
    messagingSenderId: '579134301857',
    projectId: 'studentdata-d260d',
    storageBucket: 'studentdata-d260d.firebasestorage.app',
    iosBundleId: 'com.example.gromoreApplication',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCUeGJUtcItWcSFstGLdg_bwbHnulobhQg',
    appId: '1:579134301857:ios:af306925da786f343e72e0',
    messagingSenderId: '579134301857',
    projectId: 'studentdata-d260d',
    storageBucket: 'studentdata-d260d.firebasestorage.app',
    iosBundleId: 'com.example.gromoreApplication',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC1ROaS_TAq55U2ITQk_D0K0ppyRp4Kns8',
    appId: '1:579134301857:web:943fe8473706331f3e72e0',
    messagingSenderId: '579134301857',
    projectId: 'studentdata-d260d',
    authDomain: 'studentdata-d260d.firebaseapp.com',
    storageBucket: 'studentdata-d260d.firebasestorage.app',
    measurementId: 'G-VPS8JVKRTC',
  );
}
